### ISSUE TITLE
GSAT使用

### ISSUE THREAD

**Issue by JiachengSong** [NSSL-SJTU/HermesSim#1]
您好，在使用GSAT的时候，需要配置什么环境吗，我使用您所给的gast.jar文件，会出现java.lang.NullPointerException: Cannot invoke "ghidra.program.model.listing.Program.createPrivateEventQueue(ghidra.framework.model.DomainObjectListener, int)" because "program" is null
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.<init>(AutoAnalysisManager.java:145)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.getAnalysisManager(AutoAnalysisManager.java:983)
	at com.gsat.helper.AnalysisHelper.enableAutoAnalysisManger(AnalysisHelper.java:57)
	at com.gsat.tools.BaseTool.analyzeProgram(BaseTool.java:69)
	at com.gsat.tools.BaseTool.processBasicOptions(BaseTool.java:170)
	at com.gsat.tools.ToolFactory.initTool(ToolFactory.java:82)
	at com.gsat.Main.main(Main.java:23)
java.lang.NullPointerException: Cannot invoke "ghidra.program.model.listing.Program.createPrivateEventQueue(ghidra.framework.model.DomainObjectListener, int)" because "program" is null
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.<init>(AutoAnalysisManager.java:145)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.getAnalysisManager(AutoAnalysisManager.java:983)
	at com.gsat.helper.AnalysisHelper.enableAutoAnalysisManger(AnalysisHelper.java:57)
	at com.gsat.tools.BaseTool.analyzeProgram(BaseTool.java:69)
	at com.gsat.tools.BaseTool.processBasicOptions(BaseTool.java:170)
	at com.gsat.tools.ToolFactory.initTool(ToolFactory.java:82)
	at com.gsat.Main.main(Main.java:23)
这个错误

**Comment by whitewhite93** [comment]
请问解决了吗？

**Comment by sgfvamll** [comment]
根据报错 `because "program" is null`，猜测应该是指定的二进制文件打开失败，比如使用了不支持的文件格式或者指定了错误的加载方法等。
